# Generated by Django 4.2.7 on 2024-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
