# Generated by Django 4.2.7 on 2024-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('center_number', models.PositiveIntegerField()),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
    ]
