# Generated by Django 4.2.7 on 2024-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='center_number',
            field=models.PositiveIntegerField(help_text='Center number', max_length=7, verbose_name='Center Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='School name is also the Center name', max_length=50, verbose_name='School name'),
        ),
    ]
