# Generated by Django 4.2.7 on 2024-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject Name', max_length=50)),
                ('subject_code', models.CharField(help_text='Subject Code', max_length=10)),
            ],
        ),
    ]
