# Generated by Django 4.2.7 on 2024-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_is_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_optional',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', help_text='Is the subject optional, Yes or No', max_length=1),
        ),
    ]
